version: 0.1
log:
  fields:
    service: registry
    environment: development
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ["*"]
    Access-Control-Allow-Methods: ["HEAD", "GET", "OPTIONS", "DELETE"]
    Access-Control-Allow-Headers: ["Authorization", "Docker-Content-Digest"]
    Access-Control-Allow-Credentials: ["true"]  
    X-Content-Type-Options: ["nosniff"]
    Access-Control-Expose-Headers: ["Docker-Content-Digest"]

