version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "80:80"  
    networks:
      - exam-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: gestionEtudiant
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - exam-network
    ports:
      - "3307:3306"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s

  backend:
    image: localhost:5000/spring-boot-backend:v5
    depends_on:
      - database
    networks:
      - exam-network
    ports:
      - "8080:8080" 
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 3
          window: 30s

  frontend:
    image: localhost:5000/react-frontend:v1
    depends_on:
      - backend
    networks:
      - exam-network
    ports:
      - "3000:80" 
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 3
          window: 30s

volumes:
  mysql-data:
    driver: local

networks:
  exam-network:
    driver: overlay
