apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: exam-role
rules:
  - apiGroups: [""]  
    resources: ["pods", "services", "secrets"] 
    verbs: ["get", "list", "watch"]  
  - apiGroups: ["apps"]  
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]  
    resources: ["configmaps"]
    verbs: ["create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-rolebinding
  namespace: exam
subjects:
  - kind: User
    name: docker-desktop
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: default  
    namespace: exam
roleRef:
  kind: Role
  name: exam-role  
  apiGroup: rbac.authorization.k8s.io

